### ISSUE TITLE
[Bug]: Getting Error_0: Fail to fetch on jS database call

### ISSUE THREAD

**Issue by laurentiu-git** [supabase-community/supabase-kt#32]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

I am getting the following error when I am trying to make a database call.

```
Error_0: Fail to fetch
Error_0: Fail to fetch
	at <global>.<unknown>(C:/Users/laure/AppData/Local/Temp/_karma_webpack_467611/commons.js:82924)
```

The expected function in common 

```
expect suspend fun getUserDetails(userId: Int): UserDetails

@Serializable
data class UserDetails(
    @SerialName("user_id") val userId: Int,
    @SerialName("user_overal_review")  val userOverallReview: Float?,
    @SerialName("user_reviews_number") val userReviewsNumber: Int?,
    @SerialName("first_name")  val firstName: String,
    @SerialName("last_name")  val lastName: String,
    @SerialName("user_about_me")  val aboutMe: String?,
    @SerialName("user_other")  val other: String?
)
```

```
actual suspend fun getUserDetails(userId: Int): UserDetails {
    val supabaseClient = createSupabaseClient(
        "url", "apikey"
    ) {
        install(Postgrest) {
        }
    }

   val postGrestResult = supabaseClient.postgrest.from("usersdetails").select{
            eq("user_id", userId)
        }
    return postGrestResult.decodeSingle()
}
```

```
@JsExport
@ExperimentalJsExport
@Suppress("NON_EXPORTABLE_TYPE")
fun getUserDetailsPromise(userId: Int) : Promise<UserDetails> {
    return GlobalScope.promise {
        getUserDetails(userId)
    }
}
```

I am calling the `getUserDetailsPromise ` and I am receiving that error, I have a similar function for JVM and it works just fine.

Library: ` implementation("io.ktor:ktor-client-js:2.2.1")` 

### Platform(s)

Web

**Comment by brezinajn** [comment]
The problem might be that `@SerialName` is available only for JVM.

**Comment by laurentiu-git** [comment]
> The problem might be that `@SerialName` is available only for JVM.

I just removed the annotation and change the variable names to match, but I am still getting the same error

**Comment by jan-tennert** [comment]
Btw is there a reason you create a new supabase client every time you call the `getUserDetails` function?

**Comment by laurentiu-git** [comment]
> Reference in n

My bad, I copied the wrong library, I use that one you gave link to for JS

> Btw is there a reason you create a new supabase client every time you call the `getUserDetails` function?

No reason at all, just the way I implemented and didn't bother changing it, just testing stuff out anyway.

**Comment by jan-tennert** [comment]
Could reproduce the problem, will publish a fix in a few hours

**Comment by jan-tennert** [comment]
Fixed in 0.6.1 and 0.7.0-beta-1 (sync in progress)

**Comment by laurentiu-git** [comment]
> Should be fixed in 0.6.1 and 0.7.0-beta-1 (maven central sync in progress)

Now I am receiving this, could it be because of another issue or serialization? Tried with fetching only a string and still the same.

![image](https://user-images.githubusercontent.com/70561735/206756510-0a6a4aa6-c1e1-410c-8d61-8310ed4dabd5.png)

**Comment by jan-tennert** [comment]
Either you received an empty array or there was a problem with serializing the list. Try `result.decodeAs<List<UserDetails>>()` to get the serialization error

**Comment by laurentiu-git** [comment]
> Either you received an empty array or there was a problem with serializing the list. Try `result.decodeAs<List<UserDetails>>()` to get the serialization error, _I should probably throw that exception instead of catching it, probably very confusing in the current state_

That's the thing, I should receive only one element so I am inclining to believe it is a serialization problem

**Comment by jan-tennert** [comment]
> > Either you received an empty array or there was a problem with serializing the list. Try `result.decodeAs<List<UserDetails>>()` to get the serialization error, _I should probably throw that exception instead of catching it, probably very confusing in the current state_
> 
> That's the thing, I should receive only one element so I am inclining to believe it is a serialization problem

Yea as I said try the method I wrote above, currently decodeSingle/decodeList catch the serialization errors which I'm going to change but using decodeAs should give you the problem

**Comment by laurentiu-git** [comment]
> > > Either you received an empty array or there was a problem with serializing the list. Try `result.decodeAs<List<UserDetails>>()` to get the serialization error, _I should probably throw that exception instead of catching it, probably very confusing in the current state_
> > 
> > 
> > That's the thing, I should receive only one element so I am inclining to believe it is a serialization problem
> 
> Yea as I said try the method I wrote above, currently decodeSingle/decodeList catch the serialization errors which I'm going to change but using decodeAs should give you the problem

![image](https://user-images.githubusercontent.com/70561735/206784782-ad98caae-d310-40e8-81c9-eab9d2d293a6.png)

This should help with fixing it
https://stackoverflow.com/questions/66690712/kotlinx-serialization-polymorphic-serializer-was-not-found-for-missing-class-di

**Comment by jan-tennert** [comment]
I'm not sure, sounds like a KotlinX Serialization issue you have to look into, postgrest-kt just uses `Json.decodeFromJsonElement<>()` which should work with normal data classes and definitely lists
[See code](https://github.com/supabase-community/supabase-kt/blob/a7e714ad620fb53ab742e50f8200cc93383ec029/Postgrest/src/commonMain/kotlin/io/github/jan/supabase/postgrest/query/PostgrestResult.kt#L16)
